server:
  port: 3333

spring:
  application:
    name: service-consumer
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      label: master
      profile: dev

#spring.cloud.config.discovery.enabled 是非从配置中心读取文件
#spring.cloud.config.discovery.serviceId 配置中心的servieId，即服务名


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

