version: "3"
services:
  web:
    image: riwcwt/web:1.2
    networks:
      - cluster-network
    ports:
      - 8080
    # service deployment
    deploy:
      mode: replicated
      replicas: 2
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.5'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 120s
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == worker]
  proxy:
    image: riwcwt/proxy:1.0
    networks:
      - cluster-network
    depends_on:
      - web
    ports:
      - 80:80
    # service deployment
    deploy:
      mode: replicated
      replicas: 2
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.5'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 120s
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == worker]
networks:
  cluster-network:
    external: true
