version: "3"
services:
  web:
    build: ./java
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - webnet
    links:
      - web
networks:
  webnet:
    driver: bridge
